/* ============================================================
   JOBRADAR — source registry seed (DEMO MODE).
   Each entry describes how a connector would ingest jobs in
   production. Status is DEMO for all: the connector blueprint
   (method + endpoint + frequency) is defined, but live
   ingestion is not running yet.
   ============================================================ */

import type { SourceDef } from './types';

const scan = (minutesAgo: number): string =>
  new Date(Date.now() - minutesAgo * 60e3).toISOString();

const DEMO_NOTE = 'Demo mode — connector blueprint ready.';

export const SOURCE_SEEDS: SourceDef[] = [
  /* ---------------- ATS ---------------- */
  {
    id: 'greenhouse',
    name: 'Greenhouse',
    domain: 'boards.greenhouse.io',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'API',
    endpoint: 'https://boards-api.greenhouse.io/v1/boards/{token}/jobs',
    frequency: '15 min',
    priority: 2,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(4),
    jobsIndexed: 12483,
    errors: 0,
    notes: `${DEMO_NOTE} Public job-board API; no authentication required.`,
  },
  {
    id: 'lever',
    name: 'Lever',
    domain: 'jobs.lever.co',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'API',
    endpoint: 'https://api.lever.co/v0/postings/{site}',
    frequency: '15 min',
    priority: 2,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(6),
    jobsIndexed: 8931,
    errors: 0,
    notes: `${DEMO_NOTE} Public postings API; no authentication required.`,
  },
  {
    id: 'smartrecruiters',
    name: 'SmartRecruiters',
    domain: 'careers.smartrecruiters.com',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'API',
    endpoint: 'https://api.smartrecruiters.com/v1/companies/{company}/postings',
    frequency: '30 min',
    priority: 2,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(11),
    jobsIndexed: 15204,
    errors: 1,
    notes: `${DEMO_NOTE} Public postings API with pagination.`,
  },
  {
    id: 'ashby',
    name: 'Ashby',
    domain: 'jobs.ashbyhq.com',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'API',
    endpoint: 'https://api.ashbyhq.com/posting-api/job-board/{boardName}',
    frequency: '30 min',
    priority: 2,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(9),
    jobsIndexed: 3210,
    errors: 0,
    notes: `${DEMO_NOTE} Public posting API; clean JSON schema.`,
  },
  {
    id: 'workday',
    name: 'Workday',
    domain: 'myworkdayjobs.com',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'APPROVED_CRAWLER',
    frequency: '1 hour',
    priority: 3,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(22),
    jobsIndexed: 9840,
    errors: 2,
    notes: `${DEMO_NOTE} No public API; uses the JSON job-search endpoint that Workday career sites expose. Rate-limited.`,
  },
  {
    id: 'successfactors',
    name: 'SuccessFactors',
    domain: 'successfactors.eu',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'APPROVED_CRAWLER',
    frequency: '1 hour',
    priority: 3,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(35),
    jobsIndexed: 5210,
    errors: 1,
    notes: `${DEMO_NOTE} Career-site search API per tenant; respects robots.txt and rate limits.`,
  },
  {
    id: 'recruitee',
    name: 'Recruitee',
    domain: 'recruitee.com',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'CAREER_PAGE',
    frequency: '2 hours',
    priority: 4,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(58),
    jobsIndexed: 1874,
    errors: 0,
    notes: `${DEMO_NOTE} Structured-data parsing of public career pages.`,
  },
  {
    id: 'teamtailor',
    name: 'Teamtailor',
    domain: 'teamtailor.com',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'CAREER_PAGE',
    frequency: '2 hours',
    priority: 4,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(63),
    jobsIndexed: 2210,
    errors: 0,
    notes: `${DEMO_NOTE} Structured-data parsing of public career pages.`,
  },
  {
    id: 'personio',
    name: 'Personio',
    domain: 'personio.de',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'CAREER_PAGE',
    frequency: '2 hours',
    priority: 4,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(71),
    jobsIndexed: 1930,
    errors: 1,
    notes: `${DEMO_NOTE} Structured-data parsing of public career pages.`,
  },
  {
    id: 'bamboohr',
    name: 'BambooHR',
    domain: 'bamboohr.com',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'CAREER_PAGE',
    frequency: '4 hours',
    priority: 5,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(120),
    jobsIndexed: 1180,
    errors: 0,
    notes: `${DEMO_NOTE} Structured-data parsing of public career pages.`,
  },
  {
    id: 'icims',
    name: 'iCIMS',
    domain: 'icims.com',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'CUSTOM_CONNECTOR',
    frequency: '4 hours',
    priority: 5,
    enabled: false,
    status: 'DEMO',
    lastScan: scan(1440),
    jobsIndexed: 0,
    errors: 3,
    notes: 'Demo mode — connector blueprint ready. Disabled: iCIMS job feeds require per-customer authentication; pending approved access.',
  },
  {
    id: 'taleo',
    name: 'Taleo',
    domain: 'taleo.net',
    type: 'ATS',
    sector: 'Cross-sector',
    method: 'CUSTOM_CONNECTOR',
    frequency: '4 hours',
    priority: 6,
    enabled: false,
    status: 'DEMO',
    lastScan: scan(2880),
    jobsIndexed: 0,
    errors: 2,
    notes: 'Demo mode — connector blueprint ready. Disabled: Oracle is migrating Taleo tenants; connector on hold until migration completes.',
  },

  /* ---------------- PRIMARY ---------------- */
  {
    id: 'company-careers',
    name: 'Company Careers',
    domain: 'various',
    type: 'PRIMARY',
    sector: 'Cross-sector',
    method: 'CAREER_PAGE',
    frequency: '1 hour',
    priority: 1,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(14),
    jobsIndexed: 45230,
    errors: 0,
    notes: `${DEMO_NOTE} Generic connector for employer career pages with JSON-LD JobPosting structured data. Highest dedup priority.`,
  },

  /* ---------------- OFFICIAL ---------------- */
  {
    id: 'un-careers',
    name: 'UN Careers',
    domain: 'careers.un.org',
    type: 'OFFICIAL',
    sector: 'International Organizations',
    method: 'APPROVED_CRAWLER',
    frequency: '1 hour',
    priority: 3,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(19),
    jobsIndexed: 3120,
    errors: 0,
    notes: `${DEMO_NOTE} Inspira job listings; rate-limited crawler, public data only.`,
  },
  {
    id: 'reliefweb',
    name: 'ReliefWeb',
    domain: 'reliefweb.int',
    type: 'OFFICIAL',
    sector: 'Humanitarian',
    method: 'API',
    endpoint: 'https://api.reliefweb.int/v1/jobs',
    frequency: '1 hour',
    priority: 3,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(26),
    jobsIndexed: 1890,
    errors: 0,
    notes: `${DEMO_NOTE} Official public API for humanitarian job listings.`,
  },
  {
    id: 'eures',
    name: 'EURES',
    domain: 'eures.europa.eu',
    type: 'OFFICIAL',
    country: 'EU',
    sector: 'Cross-sector',
    method: 'API',
    endpoint: 'https://eures.europa.eu/api/jobs',
    frequency: '2 hours',
    priority: 3,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(44),
    jobsIndexed: 41200,
    errors: 1,
    notes: `${DEMO_NOTE} European Employment Services portal; public job API.`,
  },

  /* ---------------- SPECIALIST BOARDS ---------------- */
  {
    id: 'devex',
    name: 'Devex',
    domain: 'devex.com',
    type: 'SPECIALIST_BOARD',
    sector: 'International Development',
    method: 'APPROVED_CRAWLER',
    frequency: '1 hour',
    priority: 4,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(31),
    jobsIndexed: 2450,
    errors: 0,
    notes: `${DEMO_NOTE} Development-sector board; original employer URLs preserved for apply links.`,
  },
  {
    id: 'impactpool',
    name: 'Impactpool',
    domain: 'impactpool.org',
    type: 'SPECIALIST_BOARD',
    sector: 'International Organizations',
    method: 'APPROVED_CRAWLER',
    frequency: '2 hours',
    priority: 4,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(52),
    jobsIndexed: 980,
    errors: 0,
    notes: `${DEMO_NOTE} Impact-sector board; original employer URLs preserved for apply links.`,
  },
  {
    id: 'wellfound',
    name: 'Wellfound',
    domain: 'wellfound.com',
    type: 'SPECIALIST_BOARD',
    sector: 'Startups',
    method: 'APPROVED_CRAWLER',
    frequency: '1 hour',
    priority: 4,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(17),
    jobsIndexed: 12400,
    errors: 1,
    notes: `${DEMO_NOTE} Startup jobs; rate-limited, public listings only.`,
  },
  {
    id: 'we-work-remotely',
    name: 'We Work Remotely',
    domain: 'weworkremotely.com',
    type: 'SPECIALIST_BOARD',
    sector: 'Remote',
    method: 'RSS',
    endpoint: 'https://weworkremotely.com/categories/remote-programming-jobs.rss',
    frequency: '1 hour',
    priority: 4,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(23),
    jobsIndexed: 3210,
    errors: 0,
    notes: `${DEMO_NOTE} Official RSS feeds per category; lightweight and reliable.`,
  },
  {
    id: 'remote-ok',
    name: 'Remote OK',
    domain: 'remoteok.com',
    type: 'SPECIALIST_BOARD',
    sector: 'Remote',
    method: 'API',
    endpoint: 'https://remoteok.com/api',
    frequency: '1 hour',
    priority: 4,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(29),
    jobsIndexed: 4890,
    errors: 0,
    notes: `${DEMO_NOTE} Public JSON API for remote job listings.`,
  },
  {
    id: 'acca-careers',
    name: 'ACCA Careers',
    domain: 'jobs.accaglobal.com',
    type: 'SPECIALIST_BOARD',
    sector: 'Finance & Accounting',
    method: 'APPROVED_CRAWLER',
    frequency: '4 hours',
    priority: 5,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(96),
    jobsIndexed: 1760,
    errors: 0,
    notes: `${DEMO_NOTE} Finance-sector board; rate-limited, public listings only.`,
  },
  {
    id: 'efinancialcareers',
    name: 'eFinancialCareers',
    domain: 'efinancialcareers.com',
    type: 'SPECIALIST_BOARD',
    sector: 'Finance',
    method: 'APPROVED_CRAWLER',
    frequency: '2 hours',
    priority: 5,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(66),
    jobsIndexed: 8940,
    errors: 2,
    notes: `${DEMO_NOTE} Finance-sector board; rate-limited, public listings only.`,
  },
  {
    id: 'welcome-to-the-jungle',
    name: 'Welcome to the Jungle',
    domain: 'welcometothejungle.com',
    type: 'SPECIALIST_BOARD',
    country: 'France',
    sector: 'Startups',
    method: 'APPROVED_CRAWLER',
    frequency: '4 hours',
    priority: 6,
    enabled: false,
    status: 'DEMO',
    lastScan: scan(4320),
    jobsIndexed: 0,
    errors: 1,
    notes: 'Demo mode — connector blueprint ready. Disabled: crawler approval from the publisher is still pending.',
  },

  /* ---------------- AGGREGATORS ---------------- */
  {
    id: 'linkedin',
    name: 'LinkedIn',
    domain: 'linkedin.com',
    type: 'AGGREGATOR',
    sector: 'Cross-sector',
    method: 'APPROVED_CRAWLER',
    frequency: '1 hour',
    priority: 7,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(8),
    jobsIndexed: 189300,
    errors: 2,
    notes: `${DEMO_NOTE} Used for discovery; canonical apply URLs always point to the original source. Strict rate limits.`,
  },
  {
    id: 'infojobs',
    name: 'InfoJobs',
    domain: 'infojobs.net',
    type: 'AGGREGATOR',
    country: 'Spain',
    sector: 'Cross-sector',
    method: 'APPROVED_CRAWLER',
    frequency: '1 hour',
    priority: 7,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(13),
    jobsIndexed: 96400,
    errors: 0,
    notes: `${DEMO_NOTE} Spain-focused aggregator; canonical apply URLs point to the original source when known.`,
  },
  {
    id: 'indeed',
    name: 'Indeed',
    domain: 'indeed.com',
    type: 'AGGREGATOR',
    sector: 'Cross-sector',
    method: 'APPROVED_CRAWLER',
    frequency: '2 hours',
    priority: 8,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(41),
    jobsIndexed: 412800,
    errors: 3,
    notes: `${DEMO_NOTE} Discovery only; heavy dedup against primary/ATS sources. Strict rate limits.`,
  },
  {
    id: 'stepstone',
    name: 'StepStone',
    domain: 'stepstone.de',
    type: 'AGGREGATOR',
    country: 'Germany',
    sector: 'Cross-sector',
    method: 'APPROVED_CRAWLER',
    frequency: '2 hours',
    priority: 7,
    enabled: true,
    status: 'DEMO',
    lastScan: scan(48),
    jobsIndexed: 67800,
    errors: 0,
    notes: `${DEMO_NOTE} DACH-focused aggregator; canonical apply URLs point to the original source when known.`,
  },
];
